# Generated by Django 2.2.2 on 2019-09-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name_plural': 'URL表'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name_plural': '角色表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='user2role',
            options={'verbose_name_plural': '用户分配角色'},
        ),
        migrations.AddField(
            model_name='permission',
            name='caption',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
